/**
 * Standardized error codes across all modules.
 * Machine-readable domain error codes for consistent error handling and client-side logic.
 */
export enum ErrorCode {
  // Auth errors
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_ALREADY_REGISTERED = 'AUTH_EMAIL_ALREADY_REGISTERED',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_INVALID_REFRESH_TOKEN = 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_SESSION_REVOKED = 'AUTH_SESSION_REVOKED',
  AUTH_SESSION_NOT_FOUND = 'AUTH_SESSION_NOT_FOUND',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',
  AUTH_PASSWORD_REUSE = 'AUTH_PASSWORD_REUSE',
  AUTH_PASSWORD_SAME_AS_OLD = 'AUTH_PASSWORD_SAME_AS_OLD',
  AUTH_OLD_PASSWORD_INCORRECT = 'AUTH_OLD_PASSWORD_INCORRECT',
  AUTH_WEAK_PASSWORD = 'AUTH_WEAK_PASSWORD',
  AUTH_REFRESH_TOKEN_REUSE = 'AUTH_REFRESH_TOKEN_REUSE',

  // User errors
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',

  // Validation errors
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  INVALID_INPUT = 'INVALID_INPUT',

  // Resource errors
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',

  // Redis/Cache errors
  REDIS_UNAVAILABLE = 'REDIS_UNAVAILABLE',
  REDIS_OPERATION_FAILED = 'REDIS_OPERATION_FAILED',
  CACHE_MISS = 'CACHE_MISS',

  // Throttling errors
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // Idempotency errors
  IDEMPOTENCY_KEY_CONFLICT = 'IDEMPOTENCY_KEY_CONFLICT',
  IDEMPOTENCY_KEY_MISSING = 'IDEMPOTENCY_KEY_MISSING',

  // Blockchain errors
  BLOCKCHAIN_TX_FAILED = 'BLOCKCHAIN_TX_FAILED',
  BLOCKCHAIN_UNAVAILABLE = 'BLOCKCHAIN_UNAVAILABLE',

  // Inventory errors
  INVENTORY_INSUFFICIENT = 'INVENTORY_INSUFFICIENT',
  INVENTORY_RESERVATION_FAILED = 'INVENTORY_RESERVATION_FAILED',

  // Order errors
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ORDER_INVALID_STATE_TRANSITION = 'ORDER_INVALID_STATE_TRANSITION',
  ORDER_ALREADY_CANCELLED = 'ORDER_ALREADY_CANCELLED',

  // Blood request errors
  BLOOD_REQUEST_NOT_FOUND = 'BLOOD_REQUEST_NOT_FOUND',
  BLOOD_REQUEST_INVALID_STATUS = 'BLOOD_REQUEST_INVALID_STATUS',

  // Dispatch errors
  DISPATCH_NO_AVAILABLE_RIDERS = 'DISPATCH_NO_AVAILABLE_RIDERS',
  DISPATCH_ASSIGNMENT_FAILED = 'DISPATCH_ASSIGNMENT_FAILED',

  // Generic errors
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  OPERATION_TIMEOUT = 'OPERATION_TIMEOUT',
}
