export enum ActivityType {
  AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_PASSWORD_CHANGED = 'AUTH_PASSWORD_CHANGED',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_AUTO_UNLOCKED = 'AUTH_ACCOUNT_AUTO_UNLOCKED',
  AUTH_ACCOUNT_MANUALLY_UNLOCKED = 'AUTH_ACCOUNT_MANUALLY_UNLOCKED',
  PROFILE_UPDATED = 'PROFILE_UPDATED',
  PERMISSION_CHANGED = 'PERMISSION_CHANGED',
  BATCH_IMPORT = 'BATCH_IMPORT',
}
